conditions:
  - name: a
    type: manual
  - name: b
    type: and
    conditions:
      - a
      - type: manual
      - type: manual
triggers:
  - condition: a
    up:
      type: command
      command: echo
    down:
      type: command
      command: ls
